spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://:3306/cczkweb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 88

mqtt:
  broker-url: tcp://localhost:1883
  client-id: spring-client
  username: test
  password: test
  topics:
    heartbeat: device/heartbeat
    order: device/order
